spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:boilerplate_db}
    username: ${POSTGRES_USER:boilerplate}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: DEBUG
    org.springframework: INFO
    com.seudominio: DEBUG
